### ISSUE TITLE
The prism plugin not working on Cinema 4D R2023.2.1

### ISSUE THREAD

**Issue by OrlandoUtrera** [kapellan2000/Cinema#5]
The prism plugin not working on Cinema 4D R2023.2.1

![image](https://github.com/kapellan2000/Cinema/assets/7754923/a7885a62-2507-4719-8b6e-f4de137039a2)

**Comment by kapellan2000** [comment]
Unfortunately, the cinema has switched to python 3.10/8. There are some compatibility issues.
I will try to solve this problem.

At the moment, the plugin for Prism 2.0 works well   (this problem has already been resolved there)
In addition, there are many fixes

**Comment by kapellan2000** [comment]
Please check, I have made the necessary changes, but I do not currently have a license for cinema 4d to check
