### ISSUE TITLE
Media Player output following errors in the console when trying to output a playblast

### ISSUE THREAD

**Issue by Eranio-bit** [kapellan2000/Cinema#8]
PendingDeprecationWarning: Since 2024.0 BaseList2D.GetData is deprecated and will be removed in 2025.0. Use BaseList2D.GetDataInstance instead.
WARNING:default_Playblast:fmmpeg output: ['', "'\\\\...\\...\\...\\03_Production\\Shots\\ep01\\sh010\\Scenefiles\\cpt\\Cinema4D'\r\nCMD.EXE was started with the above path as the current directory.\r\nUNC paths are not supported.  Defaulting to Windows directory.\r\nffmpeg version 2022-04-03-git-1291568c98-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers\r\n  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband\r\n  libavutil      57. 24.101 / 57. 24.101\r\n  libavcodec     59. 25.100 / 59. 25.100\r\n  libavformat    59. 20.101 / 59. 20.101\r\n  libavdevice    59.  6.100 / 59.  6.100\r\n  libavfilter     8. 30.100 /  8. 30.100\r\n  libswscale      6.  6.100 /  6.  6.100\r\n  libswresample   4.  6.100 /  4.  6.100\r\n  libpostproc    56.  5.100 / 56.  5.100\r\n[image2 @ 000001c99582bc80] Could find no file with path '//.../.../.../.../.../.../03_Production/Shots/ep01/sh010/Playblasts/Cinema4D/v0002/ep01-sh010_Cinema4D_v0002.%04d.jpg' and index in the range 1001-1005\r\n//.../.../.../.../.../.../03_Production/Shots/ep01/sh010/Playblasts/Cinema4D/v0002/ep01-sh010_Cinema4D_v0002.%04d.jpg: No such file or directory\r\n"]

**Comment by kapellan2000** [comment]
bug fixed
